version: "3.9"  # optional since v1.27.0
services:
  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
  server:
    image: server
  client:
    image: client
volumes:
  logvolume01: {}
